name: Deploy to Firebase Hosting on PR
'on':
  pull_request:
    branches:
      - lab4
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LAB4_12DC4 }}'
          projectId: lab4-12dc4
          entryPoint: ./Lab4
